#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v4
# autospec commit: da8b975a5699
#
Name     : perl-MooX-Role-Parameterized
Version  : 0.501
Release  : 13
URL      : https://cpan.metacpan.org/authors/id/P/PA/PACMAN/MooX-Role-Parameterized-0.501.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PA/PACMAN/MooX-Role-Parameterized-0.501.tar.gz
Summary  : 'roles with composition parameters'
Group    : Development/Tools
License  : MIT
Requires: perl-MooX-Role-Parameterized-license = %{version}-%{release}
Requires: perl-MooX-Role-Parameterized-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Class::Method::Modifiers)
BuildRequires : perl(Import::Into)
BuildRequires : perl(Module::Runtime)
BuildRequires : perl(Moo)
BuildRequires : perl(Moo::Role)
BuildRequires : perl(MooX::BuildClass)
BuildRequires : perl(Package::Variant)
BuildRequires : perl(Role::Tiny)
BuildRequires : perl(Sub::Quote)
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Exception)
BuildRequires : perl(Test::Pod)
BuildRequires : perl(strictures)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# NAME
MooX::Role::Parameterized - roles with composition parameters
[![Kwalitee](https://cpants.cpanauthors.org/dist/MooX-Role-Parameterized.svg)](https://cpants.cpanauthors.org/dist/MooX-Role-Parameterized)
[![tests](https://github.com/peczenyj/MooX-Role-Parameterized/actions/workflows/linux.yml/badge.svg)](https://github.com/peczenyj/MooX-Role-Parameterized/actions/workflows/linux.yml)
[![tests](https://github.com/peczenyj/MooX-Role-Parameterized/actions/workflows/windows.yml/badge.svg)](https://github.com/peczenyj/MooX-Role-Parameterized/actions/workflows/windows.yml)
[![tests](https://github.com/peczenyj/MooX-Role-Parameterized/actions/workflows/macos.yml/badge.svg)](https://github.com/peczenyj/MooX-Role-Parameterized/actions/workflows/macos.yml)
[![tests](https://github.com/peczenyj/MooX-Role-Parameterized/actions/workflows/perltidy.yml/badge.svg)](https://github.com/peczenyj/MooX-Role-Parameterized/actions/workflows/perltidy.yml)
[![tests](https://github.com/peczenyj/MooX-Role-Parameterized/actions/workflows/perlcritic.yml/badge.svg)](https://github.com/peczenyj/MooX-Role-Parameterized/actions/workflows/perlcritic.yml)
[![Coverage Status](https://coveralls.io/repos/github/peczenyj/MooX-Role-Parameterized/badge.svg?branch=master)](https://coveralls.io/github/peczenyj/MooX-Role-Parameterized?branch=master)
[![license](https://img.shields.io/cpan/l/MooX-Role-Parameterized.svg)](https://github.com/peczenyj/MooX-Role-Parameterized/blob/master/LICENSE)
[![cpan](https://img.shields.io/cpan/v/MooX-Role-Parameterized.svg)](https://metacpan.org/dist/MooX-Role-Parameterized)

%package dev
Summary: dev components for the perl-MooX-Role-Parameterized package.
Group: Development
Provides: perl-MooX-Role-Parameterized-devel = %{version}-%{release}
Requires: perl-MooX-Role-Parameterized = %{version}-%{release}

%description dev
dev components for the perl-MooX-Role-Parameterized package.


%package license
Summary: license components for the perl-MooX-Role-Parameterized package.
Group: Default

%description license
license components for the perl-MooX-Role-Parameterized package.


%package perl
Summary: perl components for the perl-MooX-Role-Parameterized package.
Group: Default
Requires: perl-MooX-Role-Parameterized = %{version}-%{release}

%description perl
perl components for the perl-MooX-Role-Parameterized package.


%prep
%setup -q -n MooX-Role-Parameterized-0.501
cd %{_builddir}/MooX-Role-Parameterized-0.501

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-MooX-Role-Parameterized
cp %{_builddir}/MooX-Role-Parameterized-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-MooX-Role-Parameterized/318c832a31af2a599872a73290aff4d48928b354 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/MooX::Role::CONTRIBUTING.3
/usr/share/man/man3/MooX::Role::Parameterized.3
/usr/share/man/man3/MooX::Role::Parameterized::Mop.3
/usr/share/man/man3/MooX::Role::Parameterized::With.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-MooX-Role-Parameterized/318c832a31af2a599872a73290aff4d48928b354

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
